Jenkinsfile, README.md, release/sample-service.yaml
=> Add Jenkinsfile and initial skeleton for the EdgeX Release

Jenkinsfile, README.md, github-copy-labels.sh
See README for details on job details.
=> New pipeline to sync labels across ALL repos inside the edgexfoundry org

github-copy-labels.sh
=> add sleeps to avoid rate limiting

Jenkinsfile, release/sample-service.yaml
Update the release yaml to dry run `edgeXReleaseDockerImage`
**### Please do not merge yet. This is still under development**
=> Functional Testing - update endpoints to test release

release/device-sdk-c.yaml
=> release(geneva): Release Device C SDK

Jenkinsfile
=> add GO_PROXY

release/device-sdk-go.yaml
=> release(geneva): Release Device Go SDK (v.1.2.1)

release/device-modbus-go.yaml, release/device-mqtt-go.yaml, release/device-random.yaml, release/device-rest-go.yaml, release/device-snmp-go.yaml, release/device-virtual-go.yaml
=> release(geneva): Release Go Device Services

release/app-functions-sdk-go.yaml, release/app-service-configurable.yaml, release/device-camera-go.yaml, release/docker-edgex-consul.yaml, release/docker-edgex-mongo.yaml, release/docker-edgex-volume.yaml, release/edgex-go.yaml, release/edgex-ui-go.yaml, release/support-rulesengine.yaml
@rsdmike @iain-anderson @tsconn23 @michaelestrin @tingyuz @tonyespy 
Can you guys look at the docker images list and see if that makes sense or if I missed any for the repositories.
@ernestojeda @soda480 @bill-mahoney 
Does the YAML look good for the changes made? I tried to incorporate the refactors in. Right now everything is marked as false just to be safe.
=> Geneva Release Manifest

release/edgex-go.yaml
=>  Fix typo for docker-security-secretstore-setup-go

release/edgex-go.yaml
=> release(geneva): Release Edgex-go snap to beta and candidate channels

release/blackbox-testing.yaml, release/edgex-taf.yaml
=> release(geneva): Tag blackbox-testing and edgex-taf

release/edgex-go.yaml
=> release(geneva): Release edgex-go snap to stable channel

release/device-mqtt-go.yaml
=> release(geneva): Update device-mqtt snap

.coveragerc, .gitignore, Dockerfile, Jenkinsfile, README.md, build.py, requirements-build.txt, requirements.txt, src/main/python/githubsync/__init__.py, src/main/python/githubsync/api.py, src/main/python/githubsync/cli.py, src/unittest/python/test_api.py, src/unittest/python/test_cli.py
This update refactors the existing shell script to a Python script. The Python script implements the following enhancements/features:
- GitHub rate limiting
- - Implements Conditional Requests (via **--modified-since** argument)
- - Rate limiting is imposed on core functions
- Supports multi-processing execution (via **--procs** argument)
- Retry common occurring exceptions
- Synchronizes Milestones from source repo
- Supports paginated GitHub responses
- Dry Run execution (via **--noop** argument)
- Verbose Logging to stdout  (via **--debug** argument)
- Debug logging to logfile
- Curses screen (via **--screen** argument) …
=> Refactor to Python script

release/device-sdk-c.yaml
=> release(geneva dot): Release Device C SDK (v1.2.1)

release/app-functions-sdk-go.yaml, release/device-sdk-go.yaml
=> release(geneva dot): Release Device Go SDK (v1.2.2) and App SDK (v1.2.0)

release/app-service-configurable.yaml, release/support-rulesengine.yaml
- app-service-configurable (v1.2.0)
- support-rulesengine (v1.2.1)
=> release(geneva dot): Release App Service Configurable and Rules engine

release/edgex-go.yaml, release/edgex-ui-go.yaml
- edgex-go (v1.2.1)
- edgex-ui-go (v1.2.1)
=> release(geneva dot): Release EdgeX Core and EdgeX UI

release/app-service-configurable.yaml, release/device-camera-go.yaml, release/device-modbus-go.yaml, release/device-mqtt-go.yaml, release/device-random.yaml, release/device-rest-go.yaml, release/device-snmp-go.yaml, release/device-virtual-go.yaml, release/edgex-go.yaml
=> release(geneva dot): Re-push Docker Images to DockerHub and Nexus

release/app-service-configurable.yaml, release/device-modbus-go.yaml, release/device-mqtt-go.yaml, release/edgex-go.yaml
=> release(geneva dot): Release EdgeX Snaps to stable channels

build.py, src/main/python/githubsync/api.py, src/unittest/python/test_api.py
- Fix build error caused by a change made in the restclient upstream dependency
=> Fix error due to upstream restclient change

release/device-grove-c.yaml, release/device-virtual-go.yaml
=> release(): Release Device Grove C (1.2.0) and Device Virtual Go (1.2.2)

release/device-sdk-go.yaml
=> release(geneva dot): Release Go SDK (v1.2.3)

release/device-sdk-c.yaml
Release of device-sdk-c at the request of Iain Anderson
=> release(geneva): Release C SDK (v1.2.2)

.gitignore, Dockerfile, Jenkinsfile, README.md, build.py, requirements-build.txt, requirements.txt, src/main/python/dha/cli.py, src/unittest/python/test_cli.py
Archives a csv file in Jenkins upon demand.
https://github.com/edgexfoundry/cd-management/issues/50
Test Links :
https://jenkins.edgexfoundry.org/sandbox/view/All/job/Functional-Testing/job/test_docker_audit/36/console
No
> [INFO]  Executed 11 unit tests
> [INFO]  All unit tests passed.
> [INFO]  Overall coverage is 80%
> [INFO]  Overall coverage branch coverage is 48%
> [INFO]  Overall coverage partial branch coverage is 85%
> [INFO]  Average complexity: A (2.3333333333333335)
=> feat: Add code to simplify exporting dockerhub data for edgexfoundry.

Jenkinsfile
=> feat: pull VERSION from git-semver

Jenkinsfile
=> chore: add post section to archive build logs

release/device-camera-go.yaml, release/device-grove-c.yaml, release/device-modbus-go.yaml, release/device-mqtt-go.yaml, release/device-random.yaml, release/device-rest-go.yaml, release/device-snmp-go.yaml, release/device-virtual-go.yaml
=> release(geneva dot): updates to device services.

release/device-camera-go.yaml
=> release(geneva dot): Release device-camera-go (v1.1.2)

release/device-bacnet-c.yaml
=> release device-bacnet-c to 1.2.0

README.md, create.sh, edgexfoundry-folder.xml, edgexfoundry-org.xml
=> init: Add new files to seed a Jenkins server

release/docker-edgex-consul.yaml
Need to re-run edgex-consul due to snyk warning on prior hanoi PR.
=> release(hanoi): release edgex-consul

release/device-bacnet-c.yaml
Rerun release after fixing snyk scan.
=> release(hanoi): release device-bacnet-c

release/developer-scripts.yaml
Merge after hanoi developer-scripts [PR](https://github.com/edgexfoundry/developer-scripts/pull/343) has been merged.
=> release(hanoi): tag developer-scripts for hanoi

release/blackbox-testing.yaml, release/edgex-taf.yaml
=> release(hanoi): retag taf/blackbox

Dockerfile, build.py, src/main/python/synclabels/cli.py, src/unittest/python/test_cli.py
- Updated CLI to leverage new mpcurses API.
=> Update to leverage new mpcurses api - sync-github-labels

Dockerfile, build.py, src/main/python/prunetags/cli.py, src/unittest/python/test_cli.py
- Updated CLI to leverage new mpcurses API.
=> Update to leverage new mpcurses api - prune-github-tags

release/edgex-cli.yaml
=> release(hanoi): release edgex-cli 1.0.0

release/app-functions-sdk-go.yaml
=> release(hanoi-dot): app-functions-sdk-go release 1.3.1

release/app-service-configurable.yaml, release/edgex-cli.yaml, release/edgex-go.yaml
Hanoi-Dot release - Hold until Feb-17
Code Freeze - Feb - 10-17
Release - Feb 17.
=> release(hanoi-dot): Release manifest

release/device-grove-c.yaml
=> release(hanoi-dot): device-grove-c

release/edgex-taf.yaml
=> release(hanoi-dot): tag edgex-taf

Jenkinsfile, README.md
Limit inline Snyk docker image scans to only run weekly
Signed-off-by: Chinu Joy <chinu.joy@intel.com>
https://github.com/edgexfoundry/edgex-global-pipelines/issues/313
=> feat: Limit inline Snyk docker image scans to only run weekly

Jenkinsfile
=> Correct name of logfile

README.md, build.py, docs/images/complexity.svg, docs/images/coverage.svg, docs/images/python.svg, docs/images/severity.svg, requirements.txt, src/main/python/prunetags/cli.py
- Update build to include pybuilder plugins for `radon` (i.e. cyclomatic complexity) and `bandit`
- Add badges to readme
- Add integration with `pygfiglet` for CLI ASCII art font
=> Update build and add pyfiglet `prune-github-tags`

README.md, build.py, docs/images/complexity.svg, docs/images/coverage.svg, docs/images/python.svg, docs/images/severity.svg, requirements.txt, src/main/python/synclabels/cli.py
- Update build to include pybuilder plugins for `radon` (i.e. cyclomatic complexity) and `bandit`
- Add badges to readme
- Add integration with `pygfiglet` for CLI ASCII art font
=> Update build and add pyfiglet `sync-github-labels`

Dockerfile, README.md, build.py, docs/images/complexity.svg, docs/images/coverage.svg, docs/images/python.svg, docs/images/severity.svg, requirements-build.txt, requirements.txt, src/main/python/cr8rel/cli.py
- Update build to include pybuilder plugins for `radon` (i.e. cyclomatic complexity) and `bandit`
- Add badges to readme
- Add integration with `pygfiglet` for CLI ASCII art font
- Remove unneeded commands from Dockerfile
=> Update build and add pyfiglet `create-github-release`

Jenkinsfile
security-wg is ready to have this run weekly please
=> chore(ci): trigger the docker CIS scan on a weekly basis

build.py, src/main/python/synclabels/cli.py
Update to accommodate upstream (dependency) changes:
- mpcurses length changes - mpcurses renamed category width parameter to length
=> Update mpcurses colwidth changes

Jenkinsfile
=> ci: update to use edgex-compose repo rather than developer-scripts

Jenkinsfile
=> ci: update docker-compose URL

release/go-mod-configuration.yaml, release/go-mod-messaging.yaml, release/go-mod-registry.yaml
=> release(ireland): go-mods phase 1

release/go-mod-messaging.yaml
=> release(ireland): go-mod-messaging 2.0.1

release/go-mod-core-contracts.yaml
=> release(ireland): go-mod-core-contracts 2.0.0

release/go-mod-secrets.yaml
=> release(ireland): go-mod-secrets 2.0.0

release/app-functions-sdk-go.yaml, release/device-sdk-c.yaml, release/device-sdk-go.yaml
=> release(ireland): app and device sdk 2.0.0

release/edgex-go.yaml
=> To be merged 6/30 - release(ireland): core services 2.0.0

release/app-service-configurable.yaml
=> To be merged 6-30 - release(ireland): app services 2.0.0

release/device-camera-go.yaml, release/device-modbus-go.yaml, release/device-mqtt-go.yaml, release/device-rest-go.yaml, release/device-snmp-go.yaml, release/device-virtual-go.yaml
=> release(ireland): device services 2.0.0

release/device-mqtt-go.yaml
=> release(ireland): release device-mqtt 2.0.0

release/edgex-compose.yaml
=> release(ireland): tag edgex-compose 2.0.0

release/edgex-ui-go.yaml
=> release(ireland): edgex-ui-go 2.0.0

release/edgex-taf.yaml
=> release(ireland): tag edgex-taf 2.0.0

release/edgex-taf.yaml
=> release(ireland): update taf tag to latest

release/device-coap-c.yaml
=> release(ireland): release device-coap 2.0.0

release/device-gpio.yaml
=> release(ireland): device-gpio v1.0.0

generated-overviews/new-names/device-coap-arm64.md, generated-overviews/new-names/security-bootstrapper-arm64.md, generated-overviews/new-names/security-bootstrapper.md, generated-overviews/new-names/security-proxy-setup-arm64.md, generated-overviews/new-names/security-proxy-setup.md, generated-overviews/new-names/security-secretstore-setup-arm64.md, generated-overviews/new-names/security-secretstore-setup.md, image-overview-templates/new-names/security-bootstrapper-arm64.md, image-overview-templates/new-names/security-bootstrapper.md, image-overview-templates/new-names/security-proxy-setup-arm64.md, image-overview-templates/new-names/security-proxy-setup.md, image-overview-templates/new-names/security-secretstore-setup-arm64.md, image-overview-templates/new-names/security-secretstore-setup.md
=> fix: archive warning for new images

descriptions/image_descriptions.txt, image-overview-templates/new-names/device-coap-arm64.md, image-overview-templates/new-names/device-coap.md
=> fix: remove read-only from coap description and update Dockerfile ref

release/app-functions-sdk-go.yaml
=> release(ireland): app-function-sdk 2.0.1

README.md, build.py
=> Add badge and update build metadata

release/app-service-configurable.yaml, release/device-coap-c.yaml
=> release(ireland): app-service-configurable and device-coap-c 2.0.1

release/app-rfid-llrp-inventory.yaml, release/device-rfid-llrp-go.yaml
=> release(hanoi): rfid-llrp 1.0.0

src/main/python/prunetags/api.py, src/unittest/python/test_api.py
=> fix: update default branch to main

release/go-mod-configuration.yaml, release/go-mod-core-contracts.yaml, release/go-mod-messaging.yaml, release/go-mod-registry.yaml
=> release(jakarta): tag go-mod group 1

release/go-mod-secrets.yaml
=> release(jakarta): release go-mod-secrets

release/go-mod-bootstrap.yaml
=> release(jakarta): release go-mod-bootstrap

release/app-functions-sdk-go.yaml, release/device-sdk-c.yaml, release/device-sdk-go.yaml
=> release(jakarta): release SDKs

release/app-service-configurable.yaml
=> To be merged Nov 17th - release(Jakarta): release Jakarta app services

release/edgex-go.yaml
=> To be merged Nov 17th - release(Jakarta) release Jakarta core services

release/device-camera-go.yaml, release/device-modbus-go.yaml, release/device-mqtt-go.yaml, release/device-rest-go.yaml, release/device-snmp-go.yaml, release/device-virtual-go.yaml
=> To be merged Nov 17th - release(jakarta): release device-services

release/device-rest-go.yaml
=> release(jakarta): release device-services

release/edgex-cli.yaml, release/edgex-ui-go.yaml
=> release(jakarta): release edgex-cli, edgex-ui-go

release/edgex-taf.yaml
=> release(jakarta): tag edgex-taf tests

release/edgex-compose.yaml
=> release(jakarta): tag edgex-compose

README.md
Signed-off-by: jpwhitemn <jpwhite_mn@yahoo.com>
=> docs: update readme to include note on label synchronization

release/app-rfid-llrp-inventory.yaml, release/device-gpio.yaml, release/device-rfid-llrp-go.yaml
=> release(jakarta): Lts gpio rfid

release/device-gpio.yaml
=> release(jakarta): retrigger release of device-gpio

Jenkinsfile
Fixes #234 
This repo was causing the changelog-generator to fail in Jenkins:
https://github.com/edgexfoundry/.github
=> fix: handle empty repo names

release/go-mod-configuration.yaml, release/go-mod-core-contracts.yaml, release/go-mod-messaging.yaml, release/go-mod-registry.yaml
=> release(kamakura): go-mod group 1

release/go-mod-secrets.yaml
=> release(kamakura): go-mod group 2

release/go-mod-bootstrap.yaml
=> release(kamakura): go-mod group 3

release/app-functions-sdk-go.yaml, release/device-sdk-go.yaml
=> release(kamakura): release SDK

release/edgex-go.yaml
=> release(kamakura): release core-services

release/app-service-configurable.yaml
=> release(kamakura): release app-services

release/device-camera-go.yaml, release/device-modbus-go.yaml, release/device-mqtt-go.yaml, release/device-rest-go.yaml, release/device-virtual-go.yaml
=> release(kamakura): release device-services phase-1

release/edgex-taf.yaml
=> release(kamakura): tag TAF tests

release/edgex-cli.yaml, release/edgex-ui-go.yaml
=> release(kamakura): release ui/CLI

release/device-mqtt-go.yaml
=> release(kamakura): release device-mqtt-go

release/device-gpio.yaml, release/device-snmp-go.yaml
=> release(kamakura): gpio and snmp

build.py
=> fix: add upstream twine fix

release/device-gpio.yaml
=> release(kamakura): re-release device-gpio

release/edgex-examples.yaml
=> release(kamakura): tag edgex-examples to 2.2.0

release/edgex-docs.yaml
=> Edgex docs release for kamakura

release/app-rfid-llrp-inventory.yaml, release/device-rfid-llrp-go.yaml
=> release(kamakura): release rfid-llrp services

descriptions/image_descriptions.txt, image-overview-templates/new-names/app-rfid-llrp-inventory-arm64.md, image-overview-templates/new-names/app-rfid-llrp-inventory.md, image-overview-templates/new-names/device-rfid-llrp-arm64.md, image-overview-templates/new-names/device-rfid-llrp.md
Signed-off-by: Leonard Goodell <leonard.goodell@intel.com>
=> doc: Add/update docker images descriptions for LLRP services

release/app-service-configurable.yaml
=> release(kamakura): rerelease ASC for proper version reporting

release/go-mod-core-contracts.yaml, release/go-mod-messaging.yaml
=> release(jakarta-patch): go-mod-phase1

release/go-mod-secrets.yaml
=> release(jakarta-patch): go-mod-secrets

release/app-functions-sdk-go.yaml, release/device-sdk-go.yaml
=> release(jakarta-patch): go-sdks

Jenkinsfile
Default build, no branch specified: https://jenkins.edgexfoundry.org/sandbox/blue/organizations/jenkins/bill-changelog-generator/detail/changelog-generator/12/pipeline
`jakarta` branch specified.  Note the failures are on repositories that did not have a `jakarta` branch created: https://jenkins.edgexfoundry.org/sandbox/blue/organizations/jenkins/bill-changelog-generator/detail/changelog-generator/13/pipeline
=> build: update to allow optional branch argument

release/edgex-compose.yaml
=> release(kamakura): tag edgex-compose

Jenkinsfile, release/sample-service.yaml
=> release: sample-service lts testing

release/edgex-go.yaml
=> release(jakarta-patch): edgex-go core services

release/app-rfid-llrp-inventory.yaml, release/app-service-configurable.yaml
=> release(jakarta-patch): app services

release/device-gpio.yaml, release/device-modbus-go.yaml, release/device-mqtt-go.yaml, release/device-rest-go.yaml, release/device-rfid-llrp-go.yaml, release/device-snmp-go.yaml, release/device-virtual-go.yaml
=> release(jakarta-patch): device-services

release/device-gpio.yaml
=> release(jakarta-patch): device-gpio

release/device-mqtt-go.yaml
=> release(jakarta-patch): device-mqtt-go

release/edgex-compose.yaml
=> release(jakarta-patch): tag edgex-compose

build.py, requirements.txt, src/main/python/prepbadge/prepbadge.py
* update code to use mppbar instead of mp4ansi.
* build docker image via instructions in readme
* run container and set required environment variables
* execute test against edgexfoundry device-* repos with command `prepbadge --org edgexfoundry --branch US4643e --repos 'device-`
* replaced mp4ansi with [mppbar](https://github.com/soda480/mppbar)
=> fix: update to use mppbar instead of mp4ansi

README.md
=> docs: add summary of tools contained within

release/device-onvif-camera.yaml
Kamakura Release of:
- device-onvif-camera
=> release(kamakura): Release of device-onvif-camera service

release/device-usb-camera.yaml
=> release(kamakura): Release of device-usb-camera service

release/device-sdk-c.yaml
=> release(kamakura): Release of device-sdk-c

descriptions/image_descriptions.txt, image-overview-templates/new-names/security-spiffe-token-provider-arm64.md, image-overview-templates/new-names/security-spiffe-token-provider.md, image-overview-templates/new-names/security-spire-agent-arm64.md, image-overview-templates/new-names/security-spire-agent.md, image-overview-templates/new-names/security-spire-config-arm64.md, image-overview-templates/new-names/security-spire-config.md, image-overview-templates/new-names/security-spire-server-arm64.md, image-overview-templates/new-names/security-spire-server.md
Signed-off-by: Bryon Nevis <bryon.nevis@intel.com>
=> docs: Add descriptions of new security microservices

image-overview-templates/new-names/device-camera-arm64.md, image-overview-templates/new-names/device-camera.md, image-overview-templates/new-names/sys-mgmt-agent-arm64.md, image-overview-templates/new-names/sys-mgmt-agent.md
Signed-off-by: Leonard Goodell <leonard.goodell@intel.com>
=> docs: Add deprecation warning for device camera and sys mgmt

release/go-mod-configuration.yaml, release/go-mod-core-contracts.yaml, release/go-mod-registry.yaml
=> build: Levski release go-mod phase 1

release/go-mod-messaging.yaml, release/go-mod-secrets.yaml
=> build: levski release go-mod phase 2

release/go-mod-bootstrap.yaml
=> build: levski release go-mod boostrap

release/app-functions-sdk-go.yaml, release/device-sdk-c.yaml, release/device-sdk-go.yaml
=> Release go sdk

release/edgex-go.yaml
=> build: levski release edgex-go

release/app-rfid-llrp-inventory.yaml, release/app-service-configurable.yaml
=> build: levski release app-services

release/device-bacnet-c.yaml, release/device-coap-c.yaml, release/device-gpio.yaml, release/device-modbus-go.yaml, release/device-mqtt-go.yaml, release/device-onvif-camera.yaml, release/device-rest-go.yaml, release/device-rfid-llrp-go.yaml, release/device-snmp-go.yaml, release/device-virtual-go.yaml
=> build: levski release device services

release/device-bacnet-c.yaml
=> build: release device-bacnet

release/device-modbus-go.yaml
=> build: levski release device-modbus

release/device-mqtt-go.yaml
=> build: levski release device-mqtt

release/device-onvif-camera.yaml
=> build: levski release device-onvif

release/device-rest-go.yaml
=> build: levski release device-rest

release/device-snmp-go.yaml
=> build: levski release device-snmp

release/edgex-cli.yaml, release/edgex-ui-go.yaml
=> build:levski release cli and ui

image-overview-templates/new-names/device-bacnet.md
Signed-off-by: Leonard Goodell <leonard.goodell@intel.com>
=> docs: Add Device BACNET docker dersriptions

release/edgex-docs.yaml
=> build: levski release edgex-docs

release/edgex-examples.yaml
=> build: levski tag edgex-examples

release/edgex-taf.yaml
=> build: levski tag edgex-taf

release/edgex-compose.yaml
=> build: tag edgex-compose for levski release

release/device-bacnet-c.yaml, release/device-usb-camera.yaml
=> build: levski release bacnet-c and device-usb-camera

descriptions/image_descriptions.txt
=> add device-bacnet description

Jenkinsfile
=> ci: allow pipeline to always archive the deployment log

Jenkinsfile
=> ci: refactor post stage

release/device-sdk-go.yaml
=> build: levski patch

release/device-onvif-camera.yaml, release/device-usb-camera.yaml
=> build: levski device service patch

generated-overviews/new-names/device-onvif-camera-arm64.md, generated-overviews/new-names/device-onvif-camera.md, generated-overviews/new-names/device-usb-camera-arm64.md, generated-overviews/new-names/device-usb-camera.md
=> docs: Updated docker descriptions for Levski patch

generated-overviews/new-names/device-onvif-camera-arm64.md, generated-overviews/new-names/device-onvif-camera.md, generated-overviews/new-names/device-usb-camera-arm64.md, generated-overviews/new-names/device-usb-camera.md
=> docs: generated overviews for #324

release/app-functions-sdk-go.yaml
=> build: jakarta-patch sdk release

release/app-service-configurable.yaml
=> build: levski ASC patch

release/app-service-configurable.yaml
=> build: jakarta asc patch

release/go-mod-core-contracts.yaml
=> ci: release go-mod-contracts 3.0.0

release/go-mod-messaging.yaml
=> ci: release go-mod-messaging

release/go-mod-configuration.yaml, release/go-mod-registry.yaml, release/go-mod-secrets.yaml
=> ci: release go-mods

release/go-mod-bootstrap.yaml
=> ci: release go-mod

.chglog-default/config.yml
=> fix: try adding feat! syntax

release/go-mod-secrets.yaml
=> build: release go-mod-secrets 3.0.1

release/go-mod-bootstrap.yaml
=> build: release go-mod-boostrap 3.0.1

release/device-sdk-c.yaml
=> build: release device-sdk-c 3.0.0

release/app-functions-sdk-go.yaml, release/device-sdk-go.yaml
=> build: release go sdk's for 3.0.0

release/device-sdk-c.yaml
=> build: release device-sdk-c 3.0.1

release/edgex-go.yaml
=> build: release minnesota services (for release on 5/31)

release/app-rfid-llrp-inventory.yaml, release/app-service-configurable.yaml
=> build: release minnesota app-services (release on 5/31)

release/edgex-ui-go.yaml
=> build: Release edgex-ui-go 3.0.0

src/main/python/envbuilder/api.py
=> feat: handle non-semantic version string and add debug info

release/edgex-compose.yaml
=> build: tag edgex-compose for minnesota

release/edgex-examples.yaml
=> build: release edgex-examples for 3.0.0

release/edgex-docs.yaml
=> build: release minnesota docs

release/app-functions-sdk-go.yaml
=> build:release app-sdk-go 3.0.1

release/app-rfid-llrp-inventory.yaml, release/app-service-configurable.yaml
=> build: release app services for 3.0.1

image-overview-templates/new-names/app-rfid-llrp-inventory-arm64.md, image-overview-templates/new-names/app-rfid-llrp-inventory.md, image-overview-templates/new-names/app-service-configurable-arm64.md, image-overview-templates/new-names/app-service-configurable.md
=> docs: Add 3.0.1 patch to App service docker descriptions

generated-overviews/new-names/app-rfid-llrp-inventory-arm64.md, generated-overviews/new-names/app-rfid-llrp-inventory.md, generated-overviews/new-names/app-service-configurable-arm64.md, generated-overviews/new-names/app-service-configurable.md
=> ci: generate overviews for 3.0.1 release

release/device-uart.yaml
=> build: Release device-uart

release/device-sdk-c.yaml
=> build: release device-sdk-c 3.0.2

descriptions/image_descriptions.txt, image-overview-templates/new-names/device-uart-arm64.md, image-overview-templates/new-names/device-uart.md
Add service to descriptions/image_descriptions.txt and add MD files to image-overview-templates/new-names
Close #22 in device-uart
- [N] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [N] I am not introducing a new dependency (add notes below if you are)
- [N] I have added unit tests for the new feature or bug fix (if not, why?)
- [N] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [N] I have opened a PR for the related docs change (if not, why?)
N/A
N/A
N/A
=> feat: Add Docker Hub description for device-uart

release/device-bacnet-c.yaml, release/device-coap-c.yaml
=> ci: release device-coap device-bacnet 3.0.1

Jenkinsfile
=> feat: automatically generate overviews and push changes

Jenkinsfile
=> fix: add missing git

Dockerfile, Jenkinsfile
=> fix: install git inside image

Jenkinsfile
=> fix: move dockerfiel agent to execute stage

Jenkinsfile
=> fix: rework stages due to python issues

Jenkinsfile
=> fix: add git switch to push to correct branch

Jenkinsfile, image-overview-templates/new-names/sample-service.md
=> fix: update execute logic

.github/workflows/changelog.yml, README.md, cliff.toml
=> feat: add git-cliff changelog generator

release/go-mod-configuration.yaml, release/go-mod-core-contracts.yaml, release/go-mod-registry.yaml
=> build(napa): release go-mod-group-1

release/go-mod-messaging.yaml, release/go-mod-secrets.yaml
=> build(napa): Release go-mod-2

release/go-mod-bootstrap.yaml
=> build(napa): release go-mod-3

release/app-functions-sdk-go.yaml, release/device-sdk-go.yaml
=> build(napa): release go SDKs

release/device-sdk-c.yaml
=> build(napa): release C SDK

Jenkinsfile, release/app-record-replay.yaml, release/app-rfid-llrp-inventory.yaml, release/app-service-configurable.yaml
=> build(napa): release app-services 3.1.0

release/app-record-replay.yaml, release/app-service-configurable.yaml
=> build(napa): release app-service-config and app-record-replay

release/edgex-ui-go.yaml
=> build(napa): release edgex-ui-go

release/edgex-compose.yaml
=> build(napa): release edgex-compose

release/edgex-helm.yaml
=> build(napa): tag edgex-helm

release/edgex-taf.yaml
=> build(napa): tag edgex-taf 3.1.0

release/edgex-examples.yaml
=> build(napa): release edgex-examples

release/edgex-docs.yaml
=> build(napa): edgex-docs

image-overview-templates/new-names/sample-service.md
=> ci: add sample-service repo link

image-overview-templates/new-names/app-service-configurable-arm64.md, image-overview-templates/new-names/core-common-config-bootstrapper.md, image-overview-templates/new-names/core-data.md, image-overview-templates/new-names/core-metadata-arm64.md, image-overview-templates/new-names/device-coap-arm64.md, image-overview-templates/new-names/device-gpio-arm64.md, image-overview-templates/new-names/device-modbus-arm64.md, image-overview-templates/new-names/device-mqtt.md, image-overview-templates/new-names/device-onvif-camera-arm64.md, image-overview-templates/new-names/device-rfid-llrp-arm64.md, image-overview-templates/new-names/device-rfid-llrp.md, image-overview-templates/new-names/device-snmp.md, image-overview-templates/new-names/device-uart-arm64.md, image-overview-templates/new-names/device-usb-camera-arm64.md, image-overview-templates/new-names/edgex-ui-arm64.md, image-overview-templates/new-names/security-proxy-auth-arm64.md, image-overview-templates/new-names/security-proxy-setup-arm64.md, image-overview-templates/new-names/security-spiffe-token-provider-arm64.md, image-overview-templates/new-names/security-spire-agent-arm64.md, image-overview-templates/new-names/support-scheduler-arm64.md, image-overview-templates/new-names/support-scheduler.md
=> build(napa): update dockerhub descriptions

release/sample-service.yml
=> release: test sample service release

release/sample-service.yaml
=> ci: test release sample-service

release/app-functions-sdk-go.yaml, release/device-sdk-go.yaml
=> build: napa-patch sdk release

release/app-service-configurable.yaml
=> build(napa): app-service-config patch release

release/device-modbus-go.yaml, release/device-virtual-go.yaml
=> build(napa): device-virtual and device-modbus patch release

release/device-gpio.yaml, release/device-mqtt-go.yaml, release/device-onvif-camera.yaml, release/device-rest-go.yaml, release/device-rfid-llrp-go.yaml, release/device-snmp-go.yaml, release/device-uart.yaml, release/device-usb-camera.yaml
=> build(napa): device-services patch release

release/app-record-replay.yaml, release/app-rfid-llrp-inventory.yaml
=> build(napa): app-config patch release

release/device-sdk-c.yaml
=> build(napa): release device SDK C

release/device-sdk-c.yaml
=> build(napa): Correct commit-id of device-sdk-c

release/edgex-compose.yaml
=> build(napa): patch release edgex-compose

release/edgex-taf.yaml
=> build(napa): patch release edgex-taf

.github/workflows/changelog.yml
upload-artifact migration: https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md
=> feat: upgrade github actions to v4

release/go-mod-core-contracts.yaml
=> build(odesa): release go-mod repos 4.0.0

README.md
=> docs: add build-docker-manifests summary

release/go-mod-messaging.yaml, release/go-mod-registry.yaml, release/go-mod-secrets.yaml
=> build(odessa): release 3 go-mod repos 4.0.0

release/go-mod-bootstrap.yaml
=> build(odessa): release go-mod-bootstrap 4.0.0

release/go-mod-bootstrap.yaml
=> build(odessa): release go-mod-bootstrap 4.0.1

release/go-mod-bootstrap.yaml
=> build(odessa): release go-mod-bootstrap 4.0.2

release/go-mod-core-contracts.yaml
=> build(odessa): release go-mod-core-contracts 4.0.1

release/go-mod-registry.yaml, release/go-mod-secrets.yaml
=> build(odessa): release 2 go-mod repos 4.0.1

release/go-mod-configuration.yaml
=> build(odessa): release go-mod-configuration 4.0.1

release/go-mod-bootstrap.yaml
=> build(odessa): release go-mod-bootstrap 4.0.3

release/app-functions-sdk-go.yaml, release/device-sdk-go.yaml
=> build(odesa): release go SDKs 4.0.0

release/edgex-go.yaml
=> build(odessa): release core services 4.0.0

release/app-service-configurable.yaml
=> build(odessa): release app-service-configurable 4.0.0

release/edgex-ui-go.yaml
=> build(odessa): release ui 4.0.0

README.md, src/main/python/envbuilder/cli.py, src/unittest/python/test_cli.py, src/unittest/resources/mock-env
=> feat: update scripts and add new device services

release/app-service-configurable.yaml
=> build(odessa): release app-service-configurable 4.0.1

release/edgex-go.yaml
=> build(odessa): release core services 4.0.1

release/device-modbus-go.yaml, release/device-onvif-camera.yaml, release/device-rest-go.yaml, release/device-virtual-go.yaml
=> build(odesa): release 3 new device-services 4.0.0

release/device-gpio.yaml, release/device-mqtt-go.yaml, release/device-opc-ua.yaml, release/device-rfid-llrp-go.yaml, release/device-s7.yaml, release/device-snmp-go.yaml, release/device-uart.yaml, release/device-usb-camera.yaml
=> build(odessa): release 8 go device-services 4.0.0

release/app-record-replay.yaml, release/app-rfid-llrp-inventory.yaml
=> build(odessa): release 2 app-services 4.0.0

release/device-opc-ua.yaml
=> build(odessa): release device-opc-ua 4.0.0

release/edgex-go.yaml
=> build(odessa): re-release core services for core-keeper 4.0.0

release/app-functions-sdk-python.yaml
=> build(odessa): release app-functions-sdk-python 4.0.0

release/edgex-compose.yaml
=> build(odessa): Tag edgex-compose 4.0.0

release/edgex-docs.yaml
=> build(odessa): release edgex-docs

release/device-sdk-c.yaml
Re-trigger device-c-sdk 4.0.0 release for c-sdk pr check failure
=> build(odessa): Re-release device-c-sdk 4.0.0

release/device-sdk-c.yaml
=> build(odessa): re-release device-sdk-c 4.0.0

release/device-sdk-c.yaml
=> build(odessa): release device-sdk-c 4.0.0

release/device-bacnet-c.yaml, release/device-can.yaml, release/device-coap-c.yaml
=> build(odessa): release C device-services 4.0.0

release/edgex-taf.yaml
=> build(odessa): Tag edgex-taf 4.0.0
