edgexfoundry/cd-management

Jenkinsfile, README.md
Fixes #2 
* Phase in Ernesto's examples and add daily trigger.
* Update Readme.
Link to sandbox build: (build fails at end due to lack of credentials in sandbox).
https://jenkins.edgexfoundry.org/sandbox/job/cd-management-issue-2/16/console
=> Add jenkinsfile for edgex-go-snap-daily build job.

src/main/python/githubsync/cli.py, src/unittest/python/test_cli.py
The milestone synchronization didn't work as expected. In investigating the issue; several of the target repos already had a milestone called 'EdgeX Hanoi' which is a different name and more importantly a different milestone number than what the source repo has defined in cd-management. The GitHub API only supports getting and updating a milestone by its milestone number, for milestones GitHub uses the milestone number as the resource identifier.
https://developer.github.com/v3/issues/milestones/#get-a-milestone
https://developer.github.com/v3/issues/milestones/#update-a-milestone
Thus synchronization of milestones is going to require a bit more logic since some of the repos already have milestones created with the same milestone number …
=> Comment out milestone sync

build.py, src/main/python/githubsync/api.py, src/main/python/githubsync/cli.py, src/unittest/python/test_api.py, src/unittest/python/test_cli.py
This update addresses the issue with the synchronization of milestones. The GitHub API only supports getting and updating of milestones via their milestone number (not milestone title). https://github.com/edgexfoundry/cd-management/issues/33  
The pseudo-code below describes the updated logic for synchronizing milestones:
This update also updates exception handling so that the main process fails if any of the spawned processes have failures.
**Pseudo-Code**
```
for milestone_to_sync in milestones_to_sync
if milestone_to_sync exists in the target repo
if milestone on source repo has been modified since date provided
get the milestone id for the milestone_to_sync from the target repo
update the milestone in the target repo using its milestone id
else
create milestone on target repo
``` …
=> Fix issue with sync milestones

release/device-camera-go.yaml, release/device-modbus-go.yaml, release/device-mqtt-go.yaml, release/device-random.yaml, release/device-rest-go.yaml, release/device-snmp-go.yaml, release/device-virtual-go.yaml
- device-camera-go (v1.1.1)
- device-modbus-go (v1.2.1)
- device-mqtt-go (v1.2.1)
- device-random-go (v1.2.1)
- device-rest-go (v1.1.1)
- device-snmp-go (v1.2.1)
- device-virtual-go (v1.2.1)
=> release(geneva dot): Release Go Device Services

release/blackbox-testing.yaml, release/device-grove-c.yaml, release/edgex-taf.yaml
=> release(geneva): Release Device Grove C service (1.2.0) and Testing frameworks (1.2.1)

release/device-grove-c.yaml
=> release(geneva): Release Device Grove C Service Docker Images (1.2.0)

Jenkinsfile
This branch will build and push the `geneva` based edgex-go codebase to the `geneva/edge` snap channel.
=> add new branch to build geneva snap fix

Jenkinsfile, README.md, build.py, src/main/python/prunetags/api.py, src/main/python/prunetags/cli.py, src/unittest/python/test_api.py, src/unittest/python/test_cli.py
EdgeX DevOps: Implement ability to prune semver version tags from edgexfoundry repos with a given range.
#62 
Run with NOOP / DryRun on Sandbox server against `edgex-global-pipelines` with `--version <1.0.87`
[Sandbox Functional Test Build Link](https://jenkins.edgexfoundry.org/sandbox/view/All/job/Functional-Testing/job/prune-github-version-tags/3/console)
Piggybacks on existing GitHub API and functionality from prune-github-tags python module.
```
[INFO]  Overall coverage is 100%
[INFO]  Overall coverage branch coverage is 87%
[INFO]  Overall coverage partial branch coverage is 87%
[INFO]  Average complexity: A (3.25531914893617)
```
Closes: #62
=> EdgeX DevOps: Implement ability to prune semver version tags from edgexfoundry repos with a given range.

Jenkinsfile
--Report option only executes a report and will not execute command, regardless if --execute is specified. 
It would be nice if --report would be in addition to --execute but instead of changing the scope of the tool it's more productive to default to the --execute option when running on Jenkins by removing the --report option from the Jenkinsfile
=> fix(jenkinsfile): Remove --report option from default execution.

Dockerfile, Jenkinsfile, LICENSE, README.md, build.py, requirements-build.txt, requirements.txt, src/main/python/ghrelease/__init__.py, src/main/python/ghrelease/api.py, src/main/python/ghrelease/cli.py, src/unittest/python/test_api.py, src/unittest/python/test_cli.py
A Python script to facilitate creation of GitHub releases with assets.
This is the foundational capability required to provide our release automation the ability to create GitHub releases and upload assets/artifacts to the release..
I am leveraging the `edgeXBuildDocker` Jenkins shared library to build and publish the associated docker image to Nexus directly. Doing so, eliminates the need of having to create an additional branch under `ci-build-images`  to publish the docker image. 
https://github.com/edgexfoundry/edgex-global-pipelines/issues/242
Tested Jenkinsfile on Sandbox: …
=> Add create-github-release capability

Jenkinsfile, README.md, build.py, requirements.txt, src/main/python/githubsync/api.py, src/unittest/python/test_api.py
- Fix intermittent ratelimit error - error was due to the fact that I forgot to decorate the `modified_since` method with a retry decorator.
- I cleaned up the logic so that all ratelimit requests go through the ratelimit_request method.
- Added log file as artifact to build job
- Added more debug logging statements to facilitate future troubleshooting
Fixes: https://github.com/edgexfoundry/cd-management/issues/77
=> Fix intermittent ratelimit error

Jenkinsfile
* Executing docker-bench-security checks proposed in [ADR](https://github.com/edgexfoundry/edgex-docs/pull/220) on [EdgeX Foundry stack](https://github.com/edgexfoundry/developer-scripts/blob/master/releases/nightly-build/compose-files/docker-compose-nexus.yml).
* Publish all the logs to nexus for archival.
* [Build info](https://jenkins.edgexfoundry.org/sandbox/blue/organizations/jenkins/Functional-Testing%2Fvenkat-edgex-cis-benchmark-v2/detail/venkat-edgex-cis-benchmark-v2/2/)
=> run docker-bench-security checks against EdgeX stack

release/app-functions-sdk-go.yaml, release/device-sdk-c.yaml, release/device-sdk-go.yaml
@iain-anderson , @rsdmike , can you both look to ensure this SDK release looks good? For SDK's we just tag the repo.
CC: @jpwhitemn , @lenny-intel 
device-sdk-c (v1.3.0)
device-sdk-go (v1.3.0)
app-functions-sdk-go (v1.3.0)
Scheduled for release Nov 11th
=> release (hanoi): Release Device and Application SDKs

release/device-bacnet-c.yaml, release/device-camera-go.yaml, release/device-grove-c.yaml, release/device-modbus-go.yaml, release/device-mqtt-go.yaml, release/device-random.yaml, release/device-rest-go.yaml, release/device-snmp-go.yaml, release/device-virtual-go.yaml
@iain-anderson , can you look at this release manifest for device services for Hanoi and see how it looks? Pay special attention to the device-service names and version numbers to ensure they're what we want to release with Hanoi.
CC: @lenny-intel , @jpwhitemn 
device-bacnet-c (v1.3.0)
device-camera-go (v1.2.0)
device-grove-c (v1.3.0)
device-modbus-go (v1.3.0)
device-mqtt-go (v1.3.0)
device-random-go (v1.3.0)
device-rest-go (v1.2.0)
device-snmp-go (v1.3.0)
device-virtual-go (v1.3.0)
To be merged Nov 18th pending Device Service WG approval.
=> release(hanoi): Release Device Services

release/blackbox-testing.yaml, release/edgex-taf.yaml
Prepped for merging after Hanoi release.
This will tag the blackbox and taf repos to associate them with Hanoi (1.3.0)
=> release(hanoi): Tag blackbox-testing and edgex-taf

release/edgex-cli.yaml
This is a bit quirky for a archive artifact release vs a docker image release but I believe this will work and trigger build 39 (which is the next build #) on edgex-cli and create artifacts with version 1.0.0.  It will then release them from those URLs.
If this is too much going on for one PR,  I can break it up into a build/stage release PR then a release.
=> release(hanoi): release artifacts for edgex-cli

release/device-sdk-c.yaml
Take note this uses the new `commitId` recently implemented.
=> release(hanoi-dot): release device-sdk-c v1.3.1

Dockerfile, Jenkinsfile, README.md, deploy-overviews.py
Added the following items to facilitate updating the respective Docker image descriptions in DockerHub from the generated overviews:
1. `deploy-overviews.py` a Python script that iterates over a specified folder containing markdown overviews  and consumes the DockerHub API to update the respective Docker image.
* the script extracts the required DockerHub credentials from the specified Maven settings file
* the script supports targeting execution on all files discovered in the overviews folder or a subset of them by specifying a regex  to match
* includes NOOP feature to execute without making any updates to the targeted DockerHub images
2. `Dockerfile` to produce the Docker image under which the Python script will execute.
* Alpine-based with only one requirement
3. `Jenkinsfile` …
=> Add ability to deploy Docker description overviews to DockerHub

release/device-bacnet-c.yaml, release/device-camera-go.yaml, release/device-modbus-go.yaml, release/device-mqtt-go.yaml, release/device-random.yaml, release/device-rest-go.yaml, release/device-snmp-go.yaml, release/device-virtual-go.yaml
We're now ready to go with the dot releases of the device services. 
These all just come from the HEAD of the master branches, versions are as follows:
device-modbus-go  v1.3.1
device-mqtt-go   v1.3.1
device-random  v1.3.1
device-virtual-go v1.3.1
device-snmp-go v1.3.1
device-bacnet-c v1.3.1
device-rest-go v1.2.1
device-camera-go  v1.2.1
Releasing device-grove-c v1.3.1in a different PR, it's not ready right now.
=> release: device services

Dockerfile, Jenkinsfile, build.py, requirements-build.txt, src/main/python/synclabels/api.py, src/main/python/synclabels/cli.py, src/unittest/python/test_api.py, src/unittest/python/test_cli.py
- This update fixes a poorly written unit test that is causing the daily build for `git-label-sync` to fail due to an upstream change made in `github3api`.  
[Build 360](https://jenkins.edgexfoundry.org/view/EdgeX%20Foundry%20Project/job/edgexfoundry/job/cd-management/job/git-label-sync/360/)
The upstream change made to `github3api` was to add a retry for `ChunkedEncodingError` exception which has been recently occurring:
[Build 359](https://jenkins.edgexfoundry.org/view/EdgeX%20Foundry%20Project/job/edgexfoundry/job/cd-management/job/git-label-sync/359/)
[Build 357](https://jenkins.edgexfoundry.org/view/EdgeX%20Foundry%20Project/job/edgexfoundry/job/cd-management/job/git-label-sync/357/)
The root cause of the encoding error is not yet known, it seems to be happening intermittently but …
=> Fix run-time SSL error and build-time error - sync-github-labels

Dockerfile, build.py, requirements-build.txt, src/main/python/prunetags/cli.py, src/unittest/python/test_cli.py
- Fix runtime SSLerror `SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC decryption failed or bad record mac` caused by recent upstream change to `rest3client` to leverage Sessions. Each process will establish its own connection to GitHub and connections (session) are no longer shared between processes (threads). Note, the script is currently resilient enough to mitigate the SSLerror (via retry) but I prefer to make this change to not have the script retry as it appears to be less efficient and pollutes the logs.  More info on the error: 
https://stackoverflow.com/questions/3724900/python-ssl-problem-with-multiprocessing
- Remove unneeded items in Dockerfile
- Add missing build dependency to properly lint unit tests
- Fix linting errors
- Remove redundant categories in screen layout
Functional …
=> Fix run-time SSL error - prune-github-tags

Dockerfile, README.md, build.py, requirements-build.txt, src/main/python/dha/cli.py, src/unittest/python/test_cli.py
- update spawned processes to make their own connection to DockerHub API - mitigate request Session `SSLerror`
- update to use current MPcurses API
- add missing flake dependency to enable proper linting of unit tests
- add status badge to readme
- remove unneeded commands from Dockerfile
- remove NOOP argument as it was not being used/required
- fix issue @bill-mahoney reported regarding MPcurses concurrency limitation
- add retry resiliency when encountering  `HTTPError: 429 Client Error: Too Many Requests for url`
Fixes #128 
=> Update so each process instantiates its own API connection and leverage updated MPcurses API

build.py, src/main/python/prunetags/api.py, src/main/python/prunetags/cli.py, src/unittest/python/test_api.py
Update to accommodate for a couple of upstream (dependency) changes:
- github3api paging changes - paging method for github3api changed
- mpcurses length changes - mpcurses renamed category width parameter to length
=> Update github3api paging and mpcurses colwidth changes

.chglog-default/CHANGELOG.tpl.md, .chglog-default/config.yml, Jenkinsfile, README.md
Periodic Jenkins job to automatically generate CHANGELOG.md files each EdgeX Foundry repository.
- Iterates through **non-archived** repositories
- Clones each repository in parallel.
- Copies CHANGELOG.tpl.md and config.yml to each repository (If one already exists in the target repository it will not overwrite it).
- Locally deletes `dev` tags.
- Generates and archives the CHANGELOG.md for each repository.
Contributing community members can download this changelog for their repository and use it as a basis for a PR to update the changelog prior to release.
This job utilizes [git-chglog](https://github.com/git-chglog/git-chglog) for CHANGELOG.md generation.
Pipeline View:
Functional Testing / Sandbox Links
[Build Console](https://jenkins.edgexfoundry.org/sandbox/job/Functional-Testing/job …
=> feat: add changelog-generator

release/go-mod-messaging.yaml
=> release(ireland): go-mod-messaging 2.0.1

release/go-mod-bootstrap.yaml
=> release(ireland): go-mod-bootstrap 2.0.0

Jenkinsfile
The ssh key for GitHub has changed and the packer images have an old key.
https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/
This PR will just remove the key and let ssh pull the correct one.
This will remove this message in the logs:
```
08:42:15  @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
08:42:15  @       WARNING: POSSIBLE DNS SPOOFING DETECTED!          @
08:42:15  @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
08:42:15  The RSA host key for github.com has changed,
08:42:15  and the key for the corresponding IP address 140.82.114.3
08:42:15  is unknown. This could either mean that
08:42:15  DNS SPOOFING is happening or the IP address for the host
08:42:15  and its host key have changed at the same time.
08:42:15 …
```
=> fix: remove old github ssh key from known hosts to fix host mismatch error

release/edgex-go.yaml
=> build(napa): release core-services 3.1.1
